/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MarketPlaceInterface extends ethers.utils.Interface {
  functions: {
    "CreateCollection(string,string,address,uint256)": FunctionFragment;
    "admin()": FunctionFragment;
    "allCollectionsLength()": FunctionFragment;
    "collections(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CreateCollection",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allCollectionsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collections",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CreateCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allCollectionsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collections",
    data: BytesLike
  ): Result;

  events: {
    "CollectionCreated(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CollectionCreated"): EventFragment;
}

export class MarketPlace extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MarketPlaceInterface;

  functions: {
    CreateCollection(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "CreateCollection(string,string,address,uint256)"(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "admin()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    allCollectionsLength(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "allCollectionsLength()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    collections(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "collections(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  CreateCollection(
    _name: string,
    _symbol: string,
    _seller: string,
    _price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "CreateCollection(string,string,address,uint256)"(
    _name: string,
    _symbol: string,
    _seller: string,
    _price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  "admin()"(overrides?: CallOverrides): Promise<string>;

  allCollectionsLength(overrides?: CallOverrides): Promise<BigNumber>;

  "allCollectionsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  collections(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "collections(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    CreateCollection(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "CreateCollection(string,string,address,uint256)"(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    admin(overrides?: CallOverrides): Promise<string>;

    "admin()"(overrides?: CallOverrides): Promise<string>;

    allCollectionsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allCollectionsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    collections(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "collections(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    CollectionCreated(
      pair: string | null,
      seller: string | null,
      collectionId: null
    ): EventFilter;
  };

  estimateGas: {
    CreateCollection(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "CreateCollection(string,string,address,uint256)"(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    "admin()"(overrides?: CallOverrides): Promise<BigNumber>;

    allCollectionsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "allCollectionsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    collections(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collections(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CreateCollection(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "CreateCollection(string,string,address,uint256)"(
      _name: string,
      _symbol: string,
      _seller: string,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "admin()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allCollectionsLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allCollectionsLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collections(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collections(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
